### ISSUE TITLE
the window doesn't show up

### ISSUE THREAD

**Issue by mike-alex999** [textadventures/quest#1176]
Hello there here's the problem:
When i open the app the usual icon appears in the task bar but the window doesn't appear anywhere, i can't access any settings to change anything, and wen i place the mouse cursor on the icon in the task bar i see the window as transparent, i've tried uninstalling it many times, installing older versions and nothing works.

If any one knows what to do i'm all ears (eyes)

**Comment by alexwarren** [comment]
Sounds like the common Windows problem where a window has moved off-screen, rather than Quest-specific issue. Try: https://support.microsoft.com/en-gb/topic/some-programs-are-displayed-off-the-screen-b2a915b7-4705-c455-febf-8ddb6e7f0ae4#:~:text=Method%202-,Start%20the%20program.,viewable%20area%20on%20the%20screen.
