### ISSUE TITLE
My game 

### ISSUE THREAD

**Issue by Taliman880** [textadventures/quest#1184]
So when I'm trying to go from working on-line to off-line the file that I download is .quest and not .alex can you please fix this

**Comment by KVonGit** [comment]
If you still need help with this, I can probably help you out.

Make a copy of your **.quest** file. Rename the copy with the extension **.zip** instead of **.quest**.

Then, drop that **.zip** file into a reply in this thread, and it will become an attachment.

I can probably retrieve your code as an **.aslx** file from there.

---
Sorry for the late response. I don't maintain this repo or anything, but I check the issues once in a while to see I can help out from time to time.
