### ISSUE TITLE
North direction allowed when Northeast direction created

### ISSUE THREAD

**Issue by lurchie** [textadventures/quest#829]
I created the following:

    
    <asl version="550">
      <include ref="English.aslx" />
      <include ref="Core.aslx" />
      <game name="NORTHBUG">
        <gameid>e16911cc-ed6f-4492-b4cf-51d2e08211bf</gameid>
        <version>1.0</version>
        <firstpublished>2015</firstpublished>
       </game>
       <object name="room">
         <inherit name="editor_room" />
       </object>
      <object name="room1">
         <inherit name="editor_room" />
        <exit alias="northeast" to="room2">
          <inherit name="northeastdirection" />
         </exit>
        <object name="player">
          <inherit name="editor_object" />
           <inherit name="editor_player" />
         </object>
       </object>
       <object name="room2">
         <inherit name="editor_room" />
         <exit alias="southwest" to="room1">
            <inherit name="southwestdirection" />
         </exit>
       </object>
     </asl>

Here's the test:

NORTHBUG

You are in a room1.
You can go northeast.

> ne

You are in a room2.
You can go southwest.

> sw

You are in a room1.
You can go northeast.

> n

You are in a room2.
You can go southwest.

> s

You are in a room1.
You can go northeast.

[Note: It also does the same for Northwest, South and Southwest, and South and Southeast.]

**Comment by alexwarren** [comment]
This is because if the exits in the current scope include "northeast" then "n" is a valid abbreviation as it's the first letter. I can't see a straightforward fix for this as Quest always allows object and exits names to be abbreviated. When there's an actual "north" exit that exists in the scope then that is the better match "n".

If you have northeast and northwest but no north, then typing "n" asks you to choose between them. This seems reasonable to me.

So I can't see any big problem with the current behaviour and changing it is likely not to be simple.
