### ISSUE TITLE
Can't save when using web editor and playing a game

### ISSUE THREAD

**Issue by jaynabonne** [textadventures/quest#833]
If you have a game created via the web editor, while playing it via the "Play" button, typing "save" results in an error:

> save
Saving game...
Failed to save game: Failed to save game.

If you publish the game from the web editor and run the published game, it works fine.

**Comment by alexwarren** [comment]
The error message could certainly be more helpful, but note that it is by design that you cannot save while playing from the web editor, as you'd have no way of resuming the game. The only way of resuming games on the web is currently via the game listing page - when you play a game from the web editor, there's no game listing page yet.

**Comment by jaynabonne** [comment]
I'll update the issue in the forum with that explanation. Thanks, Alex!
