### ISSUE TITLE
HTTP Error 503. The service is unavailable.

### ISSUE THREAD

**Issue by Stevoruski** [textadventures/quest#993]
When I try to test my game I get this error: HTTP Error 503. The service is unavailable.

Is there a way to fix this?

**Comment by KVonGit** [comment]
Hello.

I am not affiliated with textadventures, but I believe the server which handles Quest games is currently down.  I have contacted the administrator, even though he was most assuredly already working to resolve the issue.  (He is usually ten steps ahead of me.)

---
Just for the record, the site's administrator won't see any posts here (but it is totally cool that you posted here; I'm not implying anything like that - just letting you know so the wheel turn more quickly in the future).  Quest's software maintainer runs this site.  The site administrator keeps his eye on this:

http://textadventures.co.uk/forum/site

---
Have a nice day (or night)!

Hopefully the problem is fixed soon!

**Comment by Stevoruski** [comment]
Well, thanks for the info. I think in the in-between, somehow it was just fixed. Thanks.
