### ISSUE TITLE
Update issue

### ISSUE THREAD

**Issue by Piquets** [textadventures/quest#994]
I downloaded Quest 5.7.2. Upon opening it states an update (5.7.2) is available! So I update, assuming this might be a patch, but no, it just keeps stating there is an update. Any chance of putting a stop to this?

**Comment by KVonGit** [comment]
Hello.

I don't work here, but the maintainer has announced that this will be fixed in the next release, which will *hopefully* be around the end of this month.

Also, I don't believe there is any way to fix it on your end.  The fix required numerous changes in Quest's source code.

Sorry!  (I know it's bothersome, because it bothers me, too!)

**Comment by ThePix** [comment]
I _hope_ it will be fixed, but I am not sure what caused it. I guess I missed a version number somewhere.

**Comment by Piquets** [comment]
Thank you KV and ThePix for your replies. Hope springs eternal but 'will fix' is more acceptable. ;)

**Comment by KVonGit** [comment]
Hello, again.  I hope everyone is doing well!

It appears that this issue is fixed in version 5.8.0, but no one will know for sure until it is released.

---
I'm thinking this issue can be closed?  

(It can be reopened if the problem persists in 5.8.0.)

**Comment by Piquets** [comment]
ok, closed....pending 5.8.0. ;)
